config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get '/avecwindows', to: 'static_pages#avecwindows'

  get '/exemple', to: 'static_pages#exemple'

  get '/bdd', to: 'static_pages#bdd'

  get '/console', to: 'static_pages#console'

  get '/contact', to: 'static_pages#contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
    render html: "hello, world!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def avecwindows
  end

  def exemple
  end

  def blog
  end

  def console
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://cryptic-fjord-17249.herokuapp.com//">Comment bien débuter avec Ruby on Rails</a>
  </small>
  <nav>
    <ul>
      <li><a href="https://github.com/kart-able/bien_debuter_avec_rails5/">sur GitHub</a></li>
      <li><a href="http://rubyonrails.org/">rubyonrails.org</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top">
  <div class="container-fluid">
  
		<!-- Brand/logo -->
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#example-1" aria-expanded="false">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
    <%= link_to "Home", root_path, id: "logo" %>
		</div>
		
		<!-- Collapsible Navbar -->
		<div class="collapse navbar-collapse" id="example-1">
      <ul class="nav nav-pills navbar-right">      
        <li><%= link_to "exemple", exemple_path %></li>
        <li><%= link_to "windows", avecwindows_path %></li>
        <li><%= link_to "bdd", bdd_path %></li>
        <li><%= link_to "consoles", console_path %></li>  
      </ul>
		</div>
  
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Comment bien débuter avec Ruby on Rails</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body { padding-bottom: 70px; }>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/avecwindows.html.erb
<h2>Conseils pour les utilisateurs de windows</h2>

<h3>Installez NodeJS</h3>

<p>NodeJS n'est pas requis lors de l'installation de Rails, mais vous en aurez assurément 
besoin lorsque vous voudrez passer à Bootstrap. Vous n'en voulez pas ? 
Le livre <a href="http://railstutorial.org/book/">tutoriel de Michael Hartl</a> 
en fait usage, ne soyez pas surpris à ce stade.</p>

<p>Avant même de passer à Bootstrap, un lien comme celui-ci pourra retourner une erreur : 
<br>
<span class="underligned">
link_to image_tag("rails.png", alt: "Rails logo"),
        'http://rubyonrails.org/'
</span>

<br><br>En analysant votre code, vous vous appercevrez que le problème vient de image_tag qui n'est 
pas reconnu comme une méthode par Rails. En réalité, cette méthode est mise en échec... 
Plus loin, vous aurez un problème avec stylesheet_link_tag. Même constat !</p>

<p>En suivant à la lettre le tutoriel, vous obtiendrez peut être 
<span class="underligned">Invalid CSS after "...quire bootstrap": 
expected "{", was ""</span>
<br>
<br>
Ces "erreurs" disparaîtront dès que vous aurez installé NodeJS et que vous aurez 
redémarré votre système 2 fois (je ne suis pas le seul à l'avoir expérimenté).</p>

<h3>Quelle console utiliser ?</h3>
<p>Je vous conseille au moins 2 <%= link_to "consoles", console_path %> dont une pour 
lancer le serveur. Mais sachez que si vous optez pour une console différente de celle livrée 
avec Rails, la commande 'rails console' restera figée :</p>
<p><%= image_tag("bug_console_git.png", alt: "la console git bash passe en mode inspect", 
width: "400px") %></p>
<p>LA Solution : revenir à la <%= link_to "'console rails'", console_path %></p>


<h3>platform: :mri</h3>
<p>Vérifiez que l'option :platforms => [:mri, :mingw, :x64_mingw] figure bien dans 
votre fichier Gemfile à la ligne 
<br><span class="underligned">
  gem 'byebug', platform: [:mri, :mingw, :x64_mingw]
</span>
<br><br>S'il s'y trouve 
  gem 'byebug', platform: mri
cela ne conviendra pas pour windows.</p>

<h3>Autres limitations ?</h3>
<p>
Lorsque vous parcourez le 
<a href="https://stackoverflow.com/questions/164896/limitations-in-running-ruby-rails-on-windows" alt="Limitations in running Ruby/Rails on windows">
forum de stackoverflow</a>, vous vous rendez compte qu'il y a eu de nombreux soucis au 
tout début de Rails mais que ceux-ci ont été progressivement résolus. Il en reste certes, 
mais il n'y a pas lieu de changer de système d'exploitation, tout au moins pour s'initier 
à Rails.
</p>

app/views/static_pages/bdd.html.erb
<h2>sqlite3 ou mysql ?</h2>

<p>Si vous souhaitez faire au plus simple et ne pas vous soucier de la base de données 
pour le moment, oubliez ce qui suit.</p>

<hr>

<p>Rails est livré avec sqlite3 qui se définit comme "Small. Fast. Reliable.".  
Mais Rails supporte également MySQL, PostgreSQL, SQL Server, Oracle®, Sybase, Firebird/InterBase et DB2.</p>

<p>Si comme moi, vous avez Wampserver sur votre machine, votre serveur mysql fera parfaitement 
l'affaire pour Rails. La seule chose à faire sera de configurer Rails </p>
<ul>
  <li>en ajoutant <span class="underligned">gem 'mysql2'</span> à votre Gemfile
  </li>
  <li>et avec ces quelques lignes dans le fichier config/database.yml :
  </li>
</ul>

<pre>
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost
</pre>

<p>Ne changez rien aux lignes suivantes, sauf si vous savez ce que vous faites :</p>
<pre>
development:
  <<: *default
  database: railstest_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: railstest_test

# As with config/secrets.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password as a unix environment variable when you boot
# the app. Read http://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full rundown on how to provide these environment variables in a
# production deployment.
#
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: railstest_production
  username: railstest
  password: <%= ENV['RAILSTEST_DATABASE_PASSWORD'] %>
</pre>

app/views/static_pages/console.html.erb
<h2>Les consoles</h2>

<p>Rails est livré avec une console qui permet de passer toutes les commandes dont 
vous aurez besoin, <a href="http://guides.rubyonrails.org/command_line.html">rails</a>, 
bundle, rake et même git...                                            
<br>
<%= image_tag("console_rails.png", alt: "la console rails", width: "700px") %></p>

<p>Dans la pratique, vous ouvrirez une deuxième console pour lancer le serveur rails, 
sinon vous devrez arrêter celui-ci pour pouvoir accéder à la ligne de commande. Et donc pourquoi 
ne pas opter pour une console différente ? </p>

<h3>La console Git Bash</h3>
<p>Cette console ne sert pas que pour git. Elle permet de lancer toutes les commandes rails 
<%= link_to "avec tout de même quelques limitations pour les utilisateurs de windows", avecwindows_path %>. Un petit 'truc' : 
vous pouvez la lancer sur un clic droit à l'emplacement du répertoire de votre projet.</p>

<p><%= link_to image_tag("click_droit.png", alt: "ouvrir git bash", width: "700px"), "https://git-scm.com/downloads" %></p>
<p><a href="https://git-scm.com/downloads">Lien de téléchargement</a></p>
           

app/views/static_pages/exemple.html.erb
<h1>StaticPages#exemple</h1>
<p>Find me in app/views/static_pages/exemple.html.erb</p>

<hr>

<p>Vous obtiendrez le résultat ci-dessus si vous avez créé une page 'exemple'. Et 
si vous y êtes arrivé, c'est que vous aurez suivi toutes les étapes :</p>
<ul>
  <li>créé le répertoire de votre site/app avec toute l'architecture nécessaire au fonctionnement 
  de Rails - heureusement tout se construit d'une seule ligne de commande dans la 
  <%= link_to "console", exemple_path %> : 
  <span class="underligned">rails new votre_nouveau_site</span></li>
  <li>ouvert le fichier votre_nouveau_site/config/database.yml où se trouvent notamment 
  votre username et votre password pour la connexion à la base de données (à se propos, 
  préférez vous <%= link_to "sqlite3 ou mysql", bdd_path %> ?)</li>
  <li>lancé un <span class="underligned">bundle install</span> 
  (c'est magique toutes ces 'gems' qui se chargent d'un seul click, non ?)</li>
  <li>lancé le serveur depuis la console avec <span class="underligned">
  rails server</span> (Rails est livré avec son propre serveur nommé Puma)</li>
  <li>éventuellement mis en place bootstrap, mais ce n'est pas un prérequis</li>
</ul>

<p>Si déjà vous avez pu afficher ceci, c'est que vous êtes en bonne voie...
<%= link_to image_tag("riding_rails_4th_edition_aws.png", alt: "you're on Rails", width: "200px"),
            'http://localhost:3000' %>
</p>

<p>Ce qui vous reste à faire :</p>

<ul>
  <li>générer vos pages d'un coup de <span class="underligned">rails generate controller StaticPages home example</span> 
  ce qui crée dans ce cas 2 'pages (*)' dans le répertoire /static_pages (créé automatiquement)
  </li>
  <li>vous pouvez déjà vous rendre sur la page <%= link_to "http://localhost:3000/static_pages/example", exemple_path %> 
  ou sur <%= link_to "http://localhost:3000/static_pages/home", root_path %> et c'est 
  presque fini
  </li>
  <li>dans config/routes.rb ajouter la ligne <span class="underligned">root 'static_pages#home'</span> 
  et supprimer la ligne <span class="underligned">get  'static_pages/home'</span>  <br>ATTENTION, à partir 
  de ce moment, vous ne pourrez plus utiliser l'url <%= link_to "http://localhost:3000/static_pages/home", root_path %>
  mais <%= link_to "http://localhost:3000", root_path %>
  </li>
</ul>
<br><br>
<p>Pour ajouter un minimum de navigation entre les 2 pages, il suffit d'ajouter 
<span class="underligned">&lt;%= link_to "Exemple", exemple_path %&gt;</span> 
dans la page 'Home' et <span class="underligned">&lt;%= link_to "Home", root_path %&gt;</span> 
dans la page exemple. Mais pour aller plus loin, je vous renvoie vers le <a href="http://railstutorial.org/book/">tutoriel de Michael Hartl</a></p>
<br><br>
<p>(*) En fait, ce sont plusieurs fichiers qui sont créés, pas directement des 'pages html' : 
<br>- app/controllers/static_pages_controller.rb
<br>- app/views/static_pages/home.html.erb
<br>- app/views/static_pages/example.html.erb
<br>- app/helpers/static_pages_helper.rb
<br>- app/assets/javascripts/static_pages.coffee
<br>- app/assets/stylesheets/static_pages.scss
<br>- test/controllers/static_pages_controller_test.rb
</p>
     

app/views/static_pages/home.html.erb
<h2>Comment bien débuter avec Ruby on Rails<br>(version 5)</h2>

<br><p>Ces quelques pages ont pour but de vous faire partager mon humble expérience avec Ruby on Rails.</p>
<p>La première étape pour entrer dans le vif du sujet après avoir 
<a href="http://railsinstaller.org/">installé Rails</a> 
sera de suivre l'excellent <a href="http://french.railstutorial.org/">tutoriel 
de Michael Hartl</a>. Je peux vous aider à corriger quelques erreurs qui peuvent vous 
surprendre, car l'auteur de ce livre n'a pas tout anticipé. A moins que vous ne vouliez 
faire l'expérience comme moi du forum de <a href="https://stackoverflow.com/">stackoverflow</a> 
où vous trouverez de l'aide auprès d'une large communauté de développeurs.</p>

<h3>Si vous utilisez windows</h3>
<p>Certains vous décourageront d'utiliser windows avec Rails, mais je peux vous assurer qu'il 
n'est pas nécessaire de passer à Linux ou à Mac. Suivez ces 
<%= link_to "quelques conseils", avecwindows_path %>...</p>

<h3>Vos propres pages</h3>
<p>Une fois que vous en saurez assez, vous voudrez créer vos propres pages. 
Avec Rails, la démarche sera de travailler sur la structure du site plus 
que sur le contenu dans un premier temps. 
Voici un exemple de page que vous souhaiterez obtenir : 
<%= link_to "exemple", exemple_path %> 
<br><br>
Ne soyez pas étonné, ce lien interne a été écrit comme ceci : 
<span class="underligned">
&lt;%= link_to "exemple", exemple_path %&gt; 
</span>
<br>Rien de compliqué quand on a compris qu'il faut mettre 
en jeu le routeur, d'où le 'path' (chemin en anglais). Logique ? Sinon, sans 
doute vous faut-il vous documenter sur le Modèle-vue-contrôleur...</p>

 